# ===================================================================
# Fichero de configuración Entorno Producción
# ===================================================================

# # ===============================
# = HTTP Server
# # ===============================
server:
  port: 9080

# # ===============================
# = SPRING BOOT GENERAL
# # ===============================
spring:
  config:
    activate:
      on-profile: pro